# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np
a=np.arange(15).reshape(3,5)
print('list(a)', list(a))
print('tolist()', a.tolist())

list(a) [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist() [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [ ]:
# 記得先 Import 正確的套件

import numpy as np

In [18]:

a = np.random.randint(10, size=6) 
print(a)
print(a.ndim) #有多少維度
print(a.shape) #每個維度的大小
print(a.size) #陣列中有幾個元素
print(a.dtype) #陣列中的資料型態
print(a.itemsize) #陣列中每個元素占用的空間
print(len(a)) #陣列的長度
print(type(a)) #陣列的種類

[1 6 0 4 1 9]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [17]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.ndim) #有多少維度
print(b.shape) #每個維度的大小
print(b.size) #陣列中有幾個元素
print(b.dtype) #陣列中的資料型態
print(b.itemsize) #陣列中每個元素占用的空間
print(len(b)) #陣列的長度
print(type(b)) #陣列的種類

[[1 8 6 4]
 [8 7 5 8]
 [3 1 2 7]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [19]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim) #有多少維度
print(c.shape) #每個維度的大小
print(c.size) #陣列中有幾個元素
print(c.dtype) #陣列中的資料型態
print(c.itemsize) #陣列中每個元素占用的空間
print(len(c)) #陣列的長度
print(type(c)) #陣列的種類

[[[0 6]
  [0 5]
  [7 5]]

 [[3 0]
  [0 1]
  [8 1]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [4]:
import numpy as np
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[5, 3, 3, 7, 9, 1]
[5, 3, 3, 7, 9, 1]


In [5]:
import numpy as np
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[4, 6, 1, 2], [4, 1, 2, 5], [8, 7, 2, 1]]
[array([4, 6, 1, 2]), array([4, 1, 2, 5]), array([8, 7, 2, 1])]


In [6]:

c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[6, 7], [3, 8], [5, 5]], [[7, 5], [2, 7], [1, 2]]]
[array([[6, 7],
       [3, 8],
       [5, 5]]), array([[7, 5],
       [2, 7],
       [1, 2]])]


In [9]:
def tolist(iterable):
    result=iterable.tolist()
    return(result)
    

print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 3, 3, 7, 9, 1]
[[4, 6, 1, 2], [4, 1, 2, 5], [8, 7, 2, 1]]
[[[6, 7], [3, 8], [5, 5]], [[7, 5], [2, 7], [1, 2]]]


[7, 6, 7, 3, 7, 5]
[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]


In [45]:


def tolist(iterable):
    result= iterable.tolist()
    if type(iterable)!= np.ndarray:
        return iterable
    else:
        return(result)
    
print(tolist(a))
print(tolist(b))   
print(tolist(c))    

[5, 3, 3, 7, 9, 1]
[[4, 6, 1, 2], [4, 1, 2, 5], [8, 7, 2, 1]]
[[[6, 7], [3, 8], [5, 5]], [[7, 5], [2, 7], [1, 2]]]
