# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [18]:
# 記得先 Import 正確的套件
import numpy as np 
a = np.arange(11)+1
print(a)
b = [1,1,-1,-1,-1,-1,1,1,1,1,1]
print(a*b)

[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [20]:
a[(a>=3) & (a<7)]*= -1
print(a)

[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [7]:
import numpy as np
A = np.random.rand(3, 6)
b = A[A>0.5]
print(b)
print(len(b))
print(len(A[A>0.5]))


[0.88615872 0.60920529 0.94153984 0.75351282 0.84731997 0.9437338
 0.86663622 0.68448036]
8
8
