# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [4]:
import numpy as np 
a = np.arange(6)
print(a)
print(a.sum())
print(np.sum(a))
print(sum(a))
#結果都相同，但print(a.sum()) & print(np.sum(a)) 都是只能在numpy中使用

[0 1 2 3 4 5]
15
15
15


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [14]:
# 記得先 Import 正確的套件
import numpy as np
a = np.random.random((5,5))
#也可以這樣寫 a = np.random.rand(5,5)
print(a)

[[0.82393013 0.44491998 0.21512951 0.94815809 0.03652451]
 [0.3744405  0.71419441 0.72159073 0.97581133 0.55722716]
 [0.21670708 0.63764049 0.76760756 0.1761401  0.48308949]
 [0.88779436 0.63192944 0.12182345 0.63827334 0.3581348 ]
 [0.42103239 0.74659525 0.16003094 0.77593925 0.22219303]]


In [10]:
A = np.random.random((5, 5))

A = (A - A.min())/ (A.max()- A.min())
A

array([[0.        , 0.5621096 , 0.78277833, 0.74676379, 0.81822665],
       [0.50295884, 0.86126325, 0.88892673, 0.31004229, 0.38832733],
       [0.81931053, 0.34038654, 0.40038167, 0.5404956 , 0.67919956],
       [0.21611523, 0.69827791, 0.80300804, 0.11764782, 0.28442894],
       [0.72333264, 1.        , 0.18259187, 0.46500162, 0.30929497]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [18]:
import numpy as np 
a = np.random.rand(10)
print(a)
print(a.argmax())
# a.max()=-1 #不能這樣寫 語法錯誤 需要找位置
# print(a)
a[a.argmax()]=-1
print(a)

[0.08254759 0.52883134 0.0393319  0.96438651 0.70318292 0.85967336
 0.98469063 0.74114168 0.16017031 0.85172085]
6
[ 0.08254759  0.52883134  0.0393319   0.96438651  0.70318292  0.85967336
 -1.          0.74114168  0.16017031  0.85172085]
