# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [2]:
# 記得先 Import 正確的套件
import numpy as np
import time
import timeit

In [3]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [4]:
start = time.time()
for i in Z.flat:
    i=i+1
end = time.time()
print("執行時間：%f 秒" % (end - start))


執行時間：0.890110 秒


In [5]:
start = time.time()
for i in np.nditer(Z):
    i=i+1
end = time.time()
print("執行時間：%f 秒" % (end - start))

執行時間：3.003535 秒


In [6]:
start = time.time()
for i in np.nditer(Z,order='F'):
    i=i+1
end = time.time()
print("執行時間：%f 秒" % (end - start))

執行時間：2.054045 秒


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [7]:
import numpy as np 
Z = np.random.randint(0,10,50)
print(Z)


[0 8 2 8 6 1 8 6 8 5 3 6 2 3 1 8 1 2 9 9 2 9 6 2 1 0 5 7 5 6 2 3 5 6 9 2 6
 1 4 1 2 3 9 0 4 0 2 8 9 5]


In [19]:
count=np.bincount(Z)
print(count)
print("出現最高頻率的值:",np.argmax(count))
location=np.where(Z==2)
print(location)


[4 6 9 4 2 5 7 1 6 6]
出現最高頻率的值: 2
(array([ 2, 12, 17, 20, 23, 30, 35, 40, 46], dtype=int64),)


In [13]:
'''
Your Code
'''

array([ 0,  5,  9, 10, 11, 12, 18, 22, 38, 39, 41, 47, 49])

### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [20]:
import numpy as np
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[7, 1, 0, 1, 3, 3]
[7, 1, 0, 1, 3, 3]
[[1, 2, 8, 0], [6, 0, 3, 8], [8, 3, 4, 3]]
[array([1, 2, 8, 0]), array([6, 0, 3, 8]), array([8, 3, 4, 3])]
[[[6, 0], [5, 5], [9, 7]], [[5, 4], [0, 9], [8, 8]]]
[array([[6, 0],
       [5, 5],
       [9, 7]]), array([[5, 4],
       [0, 9],
       [8, 8]])]


In [ ]:
'''
Your Code
'''